gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Project Space Taker.\p"
	.string "This game is my submission to Anthroyd's\n"
	.string "MAGM 6 game jam.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This game is segmented into five in\n"
	.string "game days.\p"
	.string "Make sure to explore all you can\n"
	.string "during each day.\p"
	.string "Enough preempting.\p"
	.string "Tell me about yourself.\p"
	.string "\n"
	.string "$"

gText_Birch_AndYouAre::
	.string "You are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who was selected to\n"
	.string "help study ongoing anomalies on\l"
	.string "Lumiour Island!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Thank you for taking the time to play\n"
	.string "Project Space Taker!\p"
	.string "I hope you enjoy it :)\p"
	.string "$"
